title: Fern & Fig
email: fernandfigcompany@gmail.com
description: Real experiences for real moms to learn from. From travel to babies and the everything in-between.
baseurl: ""
url: "https://fernandfigco.com"

theme: minima
plugins:
  - jekyll-feed
header_pages:
  - travel.md
  - life-w-baby.md
  - about.markdown
